export const MESSAGES = {
  REGISTER_SUCCESS: 'New user registered successfully!!',
  EMAIL_EXISTS: 'Email already registered!!',
  EMAIL_VERIFIED_SUCCESS: 'Email has been verified successfully!!',
  EXPIRED_TOKEN: 'Invalid or expired verification token!!',
  EMAIL_ALREADY_VERIFIED: 'Email is already verified!!',
  USER_NOT_FOUND: 'User not found!!',
  INVALID_CREDENTIALS: 'Invalid email or password!!',
  LOGIN_SUCCESS: 'Login successful!!',
  EMAIL_EXISTS: 'Email already exists!!',
  EMAIL_NOT_VERIFIED:
    'Your Email is not verified. A verification email has been sent to your inbox.Please verify before login!!',
  EMAIL_VERIFICATION_SENT: 'A verification email has been sent!!',
  REFRESH_TOKEN_REQUIRED: 'Refresh token required!!',
  INVALID_TOKEN: 'Invalid or expired refresh token!!',
  TOKEN_REFRESHED: 'Access token refreshed successfully!!',
  RESET_LINK_SENT: 'Password reset link has been sent to your email!!',
  RESET_TOKEN_REQUIRED: 'Reset password token required!!',
  PASSWORD_RESET: 'Password has been reset successfully!!',
  INVALID_OLD_PASSWORD: 'Old password is incorrect!!',
  PASSWORD_UPDATED: 'Password updated successfully!!',
};
