export const MESSAGES = {
  PROFILE_SUCCESS: 'Profile updated successfully!!',
  PROFILE_NOT_FOUND: 'User profile not found!!',
  PROFILE_GET_SUCCESS: 'User profile fetched successfully!!',
  PERSONAL_DETAILS_SUCCESS: 'Personal details updated successfully!!',
  PERSONAL_INFO_SUCCESS: 'Personal information fetched successfully!!',
  ABOUT_DETAILS_SUCCESS: 'About information fetched successfully!!',
  DOCTOR_ONLY_ALLOWED: 'Only doctors can create or manage organizations!!',
  ORGANIZATION_SUCCESS: 'Organization updated successfully!!',
  ORGANIZATION_NOT_FOUND: 'Organization not found!!',
  ORGANIZATION_GET_SUCCESS: 'Organization fetched successfully!!',
  ADMIN_ALREADY_EXISTS: 'ADMIN with this email already exists.',
  ADMIN_CREATED_SUCCESSFULLY: 'ADMIN created successfully.',
  ADMIN_UPDATED_SUCCESSFULLY: 'Patient updated successfully.',
  USER_NOT_FOUND: 'USER NOT FOUND',
  ADMIN_NOT_FOUND: 'ADMIN not found.',
  ADMINS_FETCHED_SUCCESSFULLY: 'ADMINs fetched successfully.',
  ADMIN_ALREADY_CONNECTED: 'This ADMIN is already connected to the doctor.',
  ADMIN_CONNECTED: 'This ADMIN is now connected to the doctor.',
  ADMIN_REACTIVATED:
    'The ADMIN relationship has been reactivated successfully.',
  ADMIN_DISCONNECTED: 'ADMIN has been disconnected successfully.',
  ADMIN_ALREADY_DISCONNECTED: 'ADMIN is already disconnected',
  MISSING_USER_ID: 'No User Found.',
  DOCTORS_FETCHED_SUCCESSFULLY: 'Doctors list fetched successfully',
  PATIENTS_FETCHED_SUCCESSFULLY: 'Patients list fetched successfully',
  DOCTORS_FOR_VERIFICATION_FETCHED_SUCCESSFULLY:
    'Doctors with documents for verification fetched successfully',
  DOCTOR_NO_DOCUMENTS_TO_VERIFY: 'Doctor has no uploaded documents to verify.',
  REJECTION_REASON_REQUIRED: 'Rejection reason is required for rejection.',
  INVALID_VERIFICATION_ACTION: 'Invalid action. Must be "approve" or "reject".',
  DOCTOR_DOCUMENTS_APPROVED: 'Doctor documents approved successfully.',
  DOCTOR_DOCUMENTS_REJECTED: 'Doctor documents rejected.',
  DOCTOR_ALREADY_VERIFIED: 'Doctor documents are already verified.',
  DOCTOR_ALREADY_REJECTED: 'Doctor documents are already rejected.',
  DOCTOR_NOT_FOUND: 'Doctor not found.',
  UNAUTHORIZED_NO_USER_ID: 'Unauthorized: No user ID in token.',
  ADMIN_DETAILS_FETCHED_SUCCESSFULLY: 'Admin details fetched successfully.',
  DOCTOR_NOT_FOUND_OR_MISSING_DOCS:
    'Doctor not found or has not uploaded all required documents.',
  DOCTOR_DETAILS_FETCHED_SUCCESSFULLY: 'Doctor details fetched successfully',
  INVALID_DOCTOR_ID: 'Invalid Doctor ID provided.',

  BLOG_REQUIREMENT: 'Title and description are required.',
  BLOG_POST_SUCCESS: 'Blog post created successfully.',
  BLOG_NOT_FOUND: 'Blog not found.',
  BLOG_POSTED: 'Blog post updated successfully.',
  BLOG_RETRIEVED: 'Blogs retrieved successfully.',
  BLOG_DELETED_SUCCESS: 'Blog post deleted successfully.',
  BLOG_SEARCH_ERR: 'Search query is required',
};
